// <auto-generated />

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("MicrosoftPublicApi", "RS0016:PublicSymbolsMustBeDocumented", Justification = "Analyzer currently fails to recognize the recorded API entry for the async editor method.", Scope = "member", Target = "M:LM.App.Wpf.Library.ILibraryEntryEditor.EditEntryAsync(LM.Core.Models.Entry)")]
[assembly: SuppressMessage("MicrosoftPublicApi", "RS0017:RemovePublicSymbol", Justification = "Analyzer currently fails to recognize the recorded API entry for the async editor method.", Scope = "member", Target = "M:LM.App.Wpf.Library.ILibraryEntryEditor.EditEntryAsync(LM.Core.Models.Entry)")]
[assembly: SuppressMessage("MicrosoftPublicApi", "RS0016:PublicSymbolsMustBeDocumented", Justification = "Attached property accessor recorded in PublicAPI but analyzer fails to resolve it.", Scope = "member", Target = "F:LM.App.Wpf.Views.Behaviors.DataGridColumnVisibilityBehavior.ColumnKeyProperty")]
[assembly: SuppressMessage("MicrosoftPublicApi", "RS0016:PublicSymbolsMustBeDocumented", Justification = "Attached property accessor recorded in PublicAPI but analyzer fails to resolve it.", Scope = "member", Target = "M:LM.App.Wpf.Views.Behaviors.DataGridColumnVisibilityBehavior.SetColumnKey(System.Windows.DependencyObject,System.String)")]
[assembly: SuppressMessage("MicrosoftPublicApi", "RS0016:PublicSymbolsMustBeDocumented", Justification = "Attached property accessor recorded in PublicAPI but analyzer fails to resolve it.", Scope = "member", Target = "M:LM.App.Wpf.Views.Behaviors.DataGridColumnVisibilityBehavior.GetColumnKey(System.Windows.DependencyObject)")]
